# Generated by Django 4.2.2 on 2023-06-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_remove_product_content_product_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
